version: 2.1

executors:
    python-executor:
        docker:
            - image: circleci/python:3.10
        working_directory: ~/repo

jobs:
    lint:
        executor: python-executor
        steps:
            - checkout
            - run:
                  name: Install flake8
                  command: |
                      python -m venv venv
                      . venv/bin/activate
                      pip install flake8
            - run:
                  name: Run flake8
                  command: |
                      . venv/bin/activate
                      flake8 ./src

workflows:
    version: 2
    linting_workflow:
        jobs:
            - lint
